// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package src

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func HomeTemplate() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\" class=\"bg-slate-200\"><head><title>Moujin</title><meta charset=\"UTF-8\"><meta name=\"description\" content=\"Moujin is an ongoing project. If you want to share an album or chat with connected weebz, feel free to hop in !\"><meta name=\"keywords\" content=\"Album, Music, Group\"><meta name=\"author\" content=\"Prouk (Tahon Valentin)\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link rel=\"stylesheet\" type=\"text/css\" href=\"/css/tail.css\"><script src=\"/js/htmx.min.js\"></script><script src=\"/js/main.js\"></script></head><body class=\"text-slate-700\"><img id=\"dark-mode-button\" src=\"/ass/light.svg\"><header class=\"header\"><h1 class=\"text-5xl\"><a hx-get=\"/home\" hx-trigger=\"click\" hx-target=\"#content\" hx-swap=\"innerHTML\">Moujin</a></h1></header><div id=\"content\" class=\"material-container\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = HomePage().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><footer class=\"material-container text-center\"><p>this site is an ongoing project, I don't intend to be regular with updates. I do this as a hobby.\r</p><p><a class=\"abutton\" hx-get=\"/about\" hx-trigger=\"click\" hx-target=\"#content\" hx-swap=\"innerHTML\">About</a></p><p>This work is under the wtfpl license : <a href=\"http://www.wtfpl.net/\" target=\"_blank\"><img class=\"inline\" src=\"http://www.wtfpl.net/wp-content/uploads/2012/12/wtfpl-badge-4.png\" width=\"80\" height=\"15\" alt=\"WTFPL\"></a></p></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
